export const studentWhitelist = [
    { name: "ALEJANDRO OLMEDO", email: "a.olmedo@artica.jrotero.es" },
    { name: "MAYA MONDINE", email: "m.mondine@artica.jrotero.es" },
    { name: "ARIEL CAPDEVILA", email: "a.capdevila@artica.jrotero.es" },
    { name: "JOSÉ ANTONIO GÓMEZ", email: "j.gomezdel@artica.jrotero.es" },
    { name: "DANIELA MORENO", email: "d.morenotardio@artica.jrotero.es" },
    { name: "CLOE NARVÁEZ", email: "c.narvaez@artica.jrotero.es" },
    { name: "RITA RODRÍGUEZ", email: "r.rodriguezrequena@artica.jrotero.es" },
    { name: "David Santiago Cano", email: "d.santiago@artica.jrotero.es" },
    { name: "ALBA RODRÍGUEZ", email: "a.rodriguezgarcia@artica.jrotero.es" },
    { name: "DANIELA MARQUEZ", email: "d.marquez@artica.jrotero.es" },
    { name: "LIDIA PINTO", email: "l.pinto@artica.jrotero.es" },
    { name: "Marc Andrei FRUNZAREANU", email: "m.frunzareanu@artica.jrotero.es" },
    { name: "CARMEN DE LA VEGA", email: "c.vega@artica.jrotero.es" },
    { name: "PABLO GUDIEL", email: "p.gudiel@artica.jrotero.es" },
    { name: "ALBA ORTIZ", email: "a.ortizsanchez@artica.jrotero.es" },
    { name: "ÁLVARO MATEOS", email: "a.mateosde@artica.jrotero.es" },
    { name: "ÁLVARO ANTONA", email: "a.antona@artica.jrotero.es" },
    { name: "SARA CAÑADA", email: "s.canada@artica.jrotero.es" },
    { name: "NICOLÁS SARALEGUI", email: "n.saralegui@artica.jrotero.es" },
    { name: "MARÍA CEDRÓN", email: "m.cedron@artica.jrotero.es" },
    { name: "Héctor Román Juárez", email: "h.roman@artica.jrotero.es" },
    { name: "MARCOS CUBILLO DIEGO", email: "m.cubillo@artica.jrotero.es" },
    { name: "LUCÍA ANTONA", email: "l.antona@artica.jrotero.es" },
    { name: "HUGO HERRERA", email: "h.herrera@artica.jrotero.es" },
    { name: "HUGO FERNÁNDEZ", email: "h.fernandezdamas@artica.jrotero.es" },
    { name: "HUGO MILLÁN", email: "h.millan@artica.jrotero.es" },
    { name: "JUAN FRANCISCO PLAZA", email: "j.plazaibarra@artica.jrotero.es" },
    { name: "MARCOS LOZANO", email: "m.lozanosalazar@artica.jrotero.es" },
    { name: "Camila Sofía Morán", email: "c.moran@artica.jrotero.es" },
    { name: "GONZALO ÁLVAREZ", email: "g.alvarez@artica.jrotero.es" },
    { name: "ENZO FANEGAS", email: "e.fanegas@artica.jrotero.es" },
    { name: "MARCOS CEBRIÁN", email: "m.cebrian@artica.jrotero.es" },
    { name: "MARCOS BENITO", email: "m.benitobriega@artica.jrotero.es" },
    { name: "CARLA DÍAZ", email: "c.diazabete@artica.jrotero.es" },
    { name: "IVÁN CALVO", email: "i.calvo@artica.jrotero.es" },
    { name: "IRENE GONZÁLEZ", email: "i.gonzalezdominguez@artica.jrotero.es" },
    { name: "HÉCTOR BAHAMONTES", email: "h.bahamontes@artica.jrotero.es" },
    { name: "NAIRA GRANADOS", email: "n.granados@artica.jrotero.es" },
    { name: "ALICIA TARDÓN", email: "a.tardon@artica.jrotero.es" },
    { name: "CARLA GOZALO", email: "c.gozalo@artica.jrotero.es" },
    { name: "HÉCTOR ASUNCIÓN", email: "h.asuncion@artica.jrotero.es" }
];
